ct_html db 'Content-Type: text/html', 0x0A
ct_html_size = $-ct_html

ct_css db 'Content-Type: text/css', 0x0A
ct_css_size = $-ct_css

ct_js db 'Content-Type: text/javascript', 0x0A
ct_js_size = $-ct_js

ct_jpg db 'Content-Type: image/jpeg', 0x0A
ct_jpg_size = $-ct_jpg

ct_png db 'Content-Type: image/png', 0x0A
ct_png_size = $-ct_png

ct_gif db 'Content-Type: image/gif', 0x0A
ct_gif_size = $-ct_gif

ct_swf db 'Content-Type: application/x-shockwave-flash', 0x0A
ct_swf_size = $-ct_swf
